version: '3.8'

# Development overrides for docker-compose.yml
services:
  # Override grafity service for development
  grafity:
    build:
      target: development
    environment:
      - NODE_ENV=development
      - LOG_LEVEL=debug
      - RATE_LIMIT_ENABLED=false
      - HOT_RELOAD=true
    volumes:
      - .:/app
      - /app/node_modules
      - grafity-logs:/app/logs
    ports:
      - "4000:4000"
      - "9229:9229"  # Debug port
    command: ["npm", "run", "dev"]

  # Use smaller memory settings for development
  neo4j:
    environment:
      NEO4J_server_memory_heap_initial__size: 256m
      NEO4J_server_memory_heap_max__size: 512m
      NEO4J_dbms_memory_pagecache_size: 256m
      NEO4J_dbms_memory_transaction_total_max: 512m

  # Reduce Redis memory for development
  redis:
    command: redis-server --appendonly yes --maxmemory 64mb --maxmemory-policy allkeys-lru