version: '3.8'

services:
  neo4j:
    image: neo4j:5-community
    container_name: grafity-neo4j
    restart: unless-stopped
    ports:
      - "7474:7474"  # HTTP
      - "7687:7687"  # Bolt
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_import:/var/lib/neo4j/import
      - neo4j_plugins:/plugins
    environment:
      # Authentication
      NEO4J_AUTH: neo4j/grafity123
      # Memory configuration
      NEO4J_server_memory_heap_initial__size: 512m
      NEO4J_server_memory_heap_max__size: 2G
      NEO4J_dbms_memory_pagecache_size: 1G
      # APOC plugin
      NEO4J_apoc_export_file_enabled: true
      NEO4J_apoc_import_file_enabled: true
      NEO4J_apoc_import_file_use__neo4j__config: true
      NEO4J_PLUGINS: '["apoc"]'
      # Performance settings
      NEO4J_dbms_memory_transaction_total_max: 2G
    healthcheck:
      test: ["CMD", "neo4j", "status"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  # Optional: Neo4j Browser alternative with better visualization
  neo4j-browser:
    image: neo4j/neo4j-browser:latest
    container_name: grafity-neo4j-browser
    ports:
      - "8080:80"
    environment:
      NEO4J_URL: bolt://neo4j:7687
    depends_on:
      - neo4j
    profiles:
      - browser

volumes:
  neo4j_data:
    driver: local
  neo4j_logs:
    driver: local
  neo4j_import:
    driver: local
  neo4j_plugins:
    driver: local

networks:
  default:
    name: grafity-network
    driver: bridge