apiVersion: v1
kind: Secret
metadata:
  name: grafity-secrets
  namespace: grafity
  labels:
    app: grafity
    component: secrets
type: Opaque
data:
  # Base64 encoded values - these should be generated and managed securely
  # Use: echo -n "your-secret" | base64
  JWT_SECRET: eW91ci1zdXBlci1zZWNyZXQtand0LWtleS1jaGFuZ2UtaW4tcHJvZHVjdGlvbg== # your-super-secret-jwt-key-change-in-production
  NEO4J_PASSWORD: Z3JhZml0eS1uZW80ai1wYXNzd29yZA== # grafity-neo4j-password
  GRAFANA_ADMIN_PASSWORD: Z3JhZml0eS1hZG1pbi1wYXNzd29yZA== # grafity-admin-password

---
apiVersion: v1
kind: Secret
metadata:
  name: neo4j-auth
  namespace: grafity
  labels:
    app: grafity
    component: neo4j
type: Opaque
data:
  NEO4J_AUTH: bmVvNGovZ3JhZml0eS1uZW80ai1wYXNzd29yZA== # neo4j/grafity-neo4j-password