apiVersion: v1
kind: Namespace
metadata:
  name: grafity-staging

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafity-app
spec:
  template:
    spec:
      containers:
      - name: grafity
        resources:
          requests:
            memory: "256Mi"
            cpu: "125m"
          limits:
            memory: "1Gi"
            cpu: "500m"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: neo4j
spec:
  template:
    spec:
      containers:
      - name: neo4j
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "2Gi"
            cpu: "1"

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: grafity-ingress
spec:
  rules:
  - host: grafity-staging.yourdomain.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: grafity-app
            port:
              number: 80