apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafity-app
spec:
  template:
    spec:
      containers:
      - name: grafity
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "4Gi"
            cpu: "2"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: neo4j
spec:
  template:
    spec:
      containers:
      - name: neo4j
        resources:
          requests:
            memory: "2Gi"
            cpu: "1"
          limits:
            memory: "8Gi"
            cpu: "4"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  template:
    spec:
      containers:
      - name: redis
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "1Gi"
            cpu: "1"

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: grafity-ingress
  annotations:
    nginx.ingress.kubernetes.io/rate-limit: "1000"
    nginx.ingress.kubernetes.io/rate-limit-window: "1m"
spec:
  rules:
  - host: grafity.yourdomain.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: grafity-app
            port:
              number: 80